# Generated by Django 3.1 on 2020-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
