# Generated by Django 3.2.3 on 2021-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_V2', '0003_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
