# Generated by Django 3.2.3 on 2021-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_V2', '0004_auditentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
