# Generated by Django 3.1 on 2020-08-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_link', models.CharField(max_length=200)),
                ('event_color', models.CharField(max_length=50)),
            ],
        ),
    ]
