# Generated by Django 3.1 on 2020-08-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TableV1', '0002_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TableV1.event_class')),
                ('time_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TableV1.timings')),
            ],
        ),
    ]
