# Generated by Django 3.1 on 2020-08-26 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TableV1', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_class',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TableV1.event_class'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TableV1.timings'),
        ),
    ]
