# Generated by Django 3.1 on 2020-08-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableV1', '0004_auto_20200826_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_class',
            name='owner',
        ),
    ]
