# Generated by Django 3.1 on 2020-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableV1', '0010_event_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='days',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
