# Generated by Django 3.1 on 2020-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableV1', '0013_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_class',
            name='event_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
