# Generated by Django 3.1 on 2020-09-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
                ('Course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.course')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Semester_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.semester')),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
                ('Semester_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.semester')),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Institute_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='Department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('batch_for', models.CharField(choices=[('lect', 'Lecture'), ('prac', 'Practical')], max_length=4)),
                ('Division_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.division')),
            ],
        ),
    ]
