# Generated by Django 3.1 on 2020-11-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Institute',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department')),
            ],
            options={
                'verbose_name_plural': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='Working_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.days')),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
            options={
                'verbose_name_plural': 'Working Days',
            },
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
            options={
                'verbose_name_plural': 'Timings',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timing_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.timings')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.days')),
            ],
            options={
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=20)),
                ('Branch_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.branch')),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('Institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Semester_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.semester')),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
            options={
                'verbose_name_plural': 'Division',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='Institute_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('batch_for', models.CharField(choices=[('lect', 'Lecture'), ('prac', 'Practical')], max_length=4)),
                ('Division_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.division')),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.AddConstraint(
            model_name='working_days',
            constraint=models.UniqueConstraint(fields=('Shift_id', 'Days_id'), name='Day only once for shift'),
        ),
        migrations.AddConstraint(
            model_name='timings',
            constraint=models.UniqueConstraint(fields=('name', 'Shift_id'), name='SlotName is Unique for Shift'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('name', 'Department_id'), name='ShiftName is Unique for Institute'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('short', 'Branch_id'), name='SemesterShort is Unique for Branch'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('name', 'Semester_id'), name='DivisionName is Unique for Semester'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('short', 'Institute_id'), name='DepartmentShort is Unique for Institute'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'Institute_id'), name='DepartmentName is Unique for Institute'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('name', 'Department_id'), name='BranchName is Unique for Department'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('short', 'Department_id'), name='BranchShort is Unique for Department'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('name', 'Division_id'), name='BatchName is Unique for Division'),
        ),
    ]
