# Generated by Django 3.1 on 2020-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batch'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name_plural': 'Division'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name_plural': 'Institute'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semester'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name_plural': 'Shift'},
        ),
        migrations.AlterModelOptions(
            name='slots',
            options={'verbose_name_plural': 'Slots'},
        ),
        migrations.RemoveField(
            model_name='division',
            name='short',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
