# Generated by Django 3.1 on 2020-12-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0002_auto_20201123_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.working_days'),
        ),
    ]
