# Generated by Django 3.1 on 2020-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0002_auto_20200919_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='Semester_id',
        ),
    ]
