# Generated by Django 3.1 on 2020-09-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0003_auto_20200925_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Branch_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.branch'),
        ),
    ]
