# Generated by Django 3.1 on 2020-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0003_auto_20201204_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.days'),
        ),
    ]
