# Generated by Django 3.1 on 2020-09-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0004_auto_20200925_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_details',
        ),
    ]
