# Generated by Django 3.1 on 2020-09-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0005_delete_admin_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Institute_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute'),
            preserve_default=False,
        ),
    ]
