# Generated by Django 3.1 on 2020-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0007_auto_20201006_1015'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='Short is Unique for Institute',
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('name', 'Department_id'), name='BranchName is Unique for Department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('short', 'Institute_id'), name='DepartmentShort is Unique for Institute'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'Institute_id'), name='DepartmentName is Unique for Institute'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('name', 'Department_id'), name='ShiftName is Unique for Institute'),
        ),
    ]
