# Generated by Django 3.1 on 2021-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0007_auto_20201217_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
