# Generated by Django 3.1 on 2021-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
        ('institute_V1', '0008_auto_20210105_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='subjects_for_batch',
            field=models.ManyToManyField(to='subject_V1.Subject_details'),
        ),
    ]
