# Generated by Django 3.1 on 2021-03-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
        ('institute_V1', '0009_batch_subjects_for_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='subjects_for_batch',
            field=models.ManyToManyField(blank=True, null=True, to='subject_V1.Subject_details'),
        ),
    ]
