# Generated by Django 3.1 on 2020-11-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0010_slots_is_break'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Working_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.days')),
                ('Shift_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.shift')),
            ],
            options={
                'verbose_name_plural': 'Working Days',
            },
        ),
        migrations.AddConstraint(
            model_name='working_days',
            constraint=models.UniqueConstraint(fields=('Shift_id', 'Days_id'), name='Day only once for shift'),
        ),
    ]
