# Generated by Django 3.1 on 2020-11-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0011_auto_20201108_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.working_days'),
        ),
    ]
