# Generated by Django 3.1 on 2021-03-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0013_semester_wef_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wef',
            options={'verbose_name_plural': 'WEF'},
        ),
    ]
