# Generated by Django 3.1 on 2021-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
        ('institute_V1', '0014_auto_20210326_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='subjects_for_batch',
            field=models.ManyToManyField(to='subject_V1.Subject_details'),
        ),
    ]
