# Generated by Django 3.1 on 2021-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0015_auto_20210412_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='try_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
