# Generated by Django 3.1 on 2021-05-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0017_try_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wef',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
