# Generated by Django 3.1 on 2021-05-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0018_wef_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wef',
            name='Department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
        ),
    ]
