# Generated by Django 3.2.3 on 2021-07-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0021_auto_20210525_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='WEF_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute_V1.wef'),
        ),
    ]
