# Generated by Django 3.2.3 on 2021-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0023_auto_20210823_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
