# Generated by Django 3.1 on 2020-11-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_V1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=9)),
                ('Batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.batch')),
                ('Division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.division')),
                ('Slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.slots')),
            ],
        ),
    ]
