# Generated by Django 3.1 on 2020-11-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0001_initial'),
        ('Table_V2', '0002_event_subject_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Slot_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.slots'),
        ),
    ]
