# Generated by Django 3.1 on 2020-11-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table_V2', '0003_auto_20201123_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Day',
        ),
    ]
