# Generated by Django 3.1 on 2020-12-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table_V2', '0004_remove_event_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Event'},
        ),
    ]
