# Generated by Django 3.1 on 2020-12-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0007_auto_20201217_1347'),
        ('Table_V2', '0005_auto_20201201_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Resource_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.resource'),
            preserve_default=False,
        ),
    ]
