# Generated by Django 3.1 on 2021-01-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0007_auto_20201217_1347'),
        ('Table_V2', '0006_event_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.slots'),
        ),
    ]
