# Generated by Django 3.1 on 2021-01-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0007_auto_20201217_1347'),
        ('Table_V2', '0007_auto_20210102_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Second_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Practical', to='institute_V1.slots'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='institute_V1.slots'),
        ),
    ]
