# Generated by Django 3.1 on 2021-01-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table_V2', '0008_auto_20210102_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Second_slot_id',
            new_name='Slot_id_2',
        ),
    ]
