# Generated by Django 3.1 on 2021-01-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0008_auto_20210105_1724'),
        ('Table_V2', '0009_auto_20210102_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.resource'),
        ),
    ]
