# Generated by Django 3.1 on 2021-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_V2', '0010_auto_20210107_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
