# Generated by Django 3.2.3 on 2021-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_V2', '0011_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
