# Generated by Django 3.1 on 2020-11-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_V1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('Institute_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute')),
            ],
            options={
                'verbose_name_plural': 'Faculty Designation',
            },
        ),
        migrations.CreateModel(
            name='Faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10)),
                ('Designation_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='faculty_V1.faculty_designation')),
                ('Institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute')),
                ('Shift_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.shift')),
            ],
            options={
                'verbose_name_plural': 'Faculty Details',
            },
        ),
        migrations.CreateModel(
            name='Faculty_load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_load', models.PositiveIntegerField()),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details')),
            ],
            options={
                'verbose_name_plural': 'Faculty load',
            },
        ),
        migrations.CreateModel(
            name='Can_teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details')),
            ],
            options={
                'verbose_name_plural': 'Can teach',
            },
        ),
    ]
