# Generated by Django 3.1 on 2020-09-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_V1', '0003_remove_slots_semester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Faculty details',
            },
        ),
        migrations.CreateModel(
            name='Faculty_designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('Department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty designation',
            },
        ),
    ]
