# Generated by Django 3.1 on 2020-09-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_V1', '0001_initial'),
        ('institute_V1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='Institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute'),
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='Shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.shift'),
        ),
    ]
