# Generated by Django 3.1 on 2020-11-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_V1', '0001_initial'),
        ('subject_V1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_teach',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_details'),
        ),
        migrations.AddConstraint(
            model_name='faculty_designation',
            constraint=models.UniqueConstraint(fields=('designation', 'Institute_id'), name='Designation is Unique for Institute'),
        ),
    ]
