# Generated by Django 3.1 on 2020-09-20 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0004_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty_V1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty_designation',
            options={'verbose_name_plural': 'Faculty Designation'},
        ),
        migrations.AlterModelOptions(
            name='faculty_details',
            options={'verbose_name_plural': 'Faculty Details'},
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='Designation_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='faculty_V1.faculty_designation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='Shift_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
