# Generated by Django 3.1 on 2020-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0002_auto_20200920_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField()),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details')),
            ],
            options={
                'verbose_name_plural': 'Faculty load',
            },
        ),
        migrations.CreateModel(
            name='Can_teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details')),
            ],
            options={
                'verbose_name_plural': 'Can teach',
            },
        ),
    ]
