# Generated by Django 3.1 on 2020-09-24 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty_V1', '0002_auto_20200925_0138'),
        ('institute_V1', '0001_initial'),
        ('subject_V1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty_designation',
            name='Department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
        ),
        migrations.AddField(
            model_name='can_teach',
            name='Faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details'),
        ),
        migrations.AddField(
            model_name='can_teach',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_details'),
        ),
    ]
