# Generated by Django 3.1 on 2020-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0001_initial'),
        ('faculty_V1', '0003_can_teach_faculty_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_teach',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_details'),
        ),
    ]
