# Generated by Django 3.1 on 2020-11-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0002_auto_20201123_1458'),
        ('faculty_V1', '0003_faculty_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details')),
                ('Slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.slots')),
            ],
            options={
                'verbose_name_plural': 'Not Available',
            },
        ),
    ]
