# Generated by Django 3.1 on 2020-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0003_auto_20200925_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_load',
            old_name='load',
            new_name='total_load',
        ),
    ]
