# Generated by Django 3.1 on 2020-11-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0002_auto_20201123_1458'),
        ('faculty_V1', '0004_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_details',
            name='Institute_id',
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='Department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
            preserve_default=False,
        ),
    ]
