# Generated by Django 3.1 on 2020-10-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0004_auto_20200930_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_load',
            name='total_load',
            field=models.PositiveIntegerField(),
        ),
    ]
