# Generated by Django 3.1 on 2020-10-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0006_resource_institute_id'),
        ('faculty_V1', '0005_auto_20201001_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_designation',
            name='Department_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.department'),
        ),
    ]
