# Generated by Django 3.1 on 2021-02-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0006_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
