# Generated by Django 3.1 on 2020-10-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0010_slots_is_break'),
        ('faculty_V1', '0007_auto_20201007_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_designation',
            name='Department_id',
        ),
        migrations.AddField(
            model_name='faculty_designation',
            name='Institute_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.institute'),
        ),
        migrations.AddConstraint(
            model_name='faculty_designation',
            constraint=models.UniqueConstraint(fields=('designation', 'Institute_id'), name='Designation is Unique for Institute'),
        ),
    ]
