# Generated by Django 3.1 on 2021-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0010_auto_20210320_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
