# Generated by Django 3.1 on 2021-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0013_auto_20210324_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='average',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
