# Generated by Django 3.1 on 2021-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0014_feedback_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
