# Generated by Django 3.1 on 2021-05-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
        ('faculty_V1', '0015_auto_20210326_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Event_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Subject_event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_event'),
        ),
    ]
