# Generated by Django 3.2.3 on 2021-05-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0021_auto_20210525_1530'),
        ('faculty_V1', '0016_auto_20210522_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_date', models.DateField()),
                ('WEF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.wef')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feedback_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty_V1.feedback_type'),
        ),
    ]
