# Generated by Django 3.1 on 2021-05-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
        ('faculty_V1', '0018_feedback_type_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Subject_event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_V1.subject_event'),
        ),
    ]
