# Generated by Django 3.2.3 on 2021-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0019_auto_20210526_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
