# Generated by Django 3.2.3 on 2021-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0022_alter_feedback_type_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_type',
            name='active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
