# Generated by Django 3.2.3 on 2021-06-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0023_alter_feedback_type_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_load',
            name='Faculty_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details'),
        ),
    ]
