# Generated by Django 3.2.3 on 2021-08-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0024_alter_resource_block'),
        ('faculty_V1', '0024_alter_faculty_load_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='Resource_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute_V1.resource'),
        ),
    ]
