# Generated by Django 3.2.3 on 2021-09-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_V1', '0024_alter_resource_block'),
        ('subject_V1', '0010_auto_20210729_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('other_details', models.TextField(blank=True, null=True)),
                ('Semester_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute_V1.semester')),
            ],
            options={
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Subject_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('Batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_V1.batch')),
                ('Exam_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_V1.exam')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_details')),
            ],
            options={
                'verbose_name_plural': 'Subject Exams',
            },
        ),
    ]
