# Generated by Django 3.1 on 2020-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_V1', '0004_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
                ('lect_per_week', models.IntegerField()),
                ('prac_per_week', models.IntegerField()),
                ('load_per_week', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('Sem_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institute_V1.semester')),
            ],
        ),
    ]
