# Generated by Django 3.1 on 2020-09-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_details',
            options={'verbose_name_plural': 'Subject Details'},
        ),
        migrations.RenameField(
            model_name='subject_details',
            old_name='Sem_id',
            new_name='Semester_id',
        ),
    ]
