# Generated by Django 3.1 on 2020-09-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0002_auto_20200920_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_details',
            name='lect_per_week',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject_details',
            name='load_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject_details',
            name='prac_per_week',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Subject_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('load_carried', models.PositiveIntegerField()),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_V1.subject_details')),
            ],
            options={
                'verbose_name_plural': 'Subject events',
            },
        ),
    ]
