# Generated by Django 3.1 on 2020-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0004_can_teach_subject_id'),
        ('subject_V1', '0003_auto_20200920_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_event',
            name='Faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty_V1.faculty_details'),
            preserve_default=False,
        ),
    ]
