# Generated by Django 3.1 on 2020-11-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0003_auto_20201123_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_event',
            old_name='load_carried',
            new_name='lect_carried',
        ),
        migrations.AddField(
            model_name='subject_event',
            name='prac_carried',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
