# Generated by Django 3.1 on 2020-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0004_auto_20201127_1436'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject_details',
            constraint=models.UniqueConstraint(fields=('short', 'Semester_id'), name='Subject Short is Unique for Semester.'),
        ),
        migrations.AddConstraint(
            model_name='subject_details',
            constraint=models.UniqueConstraint(fields=('name', 'Semester_id'), name='Subject Name is Unique for Semester.'),
        ),
        migrations.AddConstraint(
            model_name='subject_event',
            constraint=models.UniqueConstraint(fields=('Faculty_id', 'Subject_id'), name='Subject can have only one Unique Faculty.'),
        ),
    ]
