# Generated by Django 3.1 on 2021-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0005_auto_20201231_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_event',
            name='link',
        ),
    ]
