# Generated by Django 3.2.3 on 2021-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_V1', '0006_remove_subject_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject_event',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject_event',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
