# Generated by Django 3.2.3 on 2021-07-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_V1', '0024_alter_faculty_load_faculty_id'),
        ('subject_V1', '0007_auto_20210609_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_event',
            name='Co_faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_faculty', to='faculty_V1.faculty_details'),
        ),
        migrations.AlterField(
            model_name='subject_event',
            name='Faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_faculty', to='faculty_V1.faculty_details'),
        ),
    ]
