# Generated by Django 3.1 on 2021-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
