# Generated by Django 3.2.3 on 2021-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0002_student_details_display_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='Batch_id',
            new_name='prac_batch',
        ),
    ]
