# Generated by Django 3.2.3 on 2021-05-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_V1', '0021_auto_20210525_1530'),
        ('student_V1', '0003_rename_batch_id_student_details_prac_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='lect_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_batch+', to='institute_V1.batch'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='prac_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_batch+', to='institute_V1.batch'),
        ),
    ]
