# Generated by Django 3.2.3 on 2021-07-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0005_student_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_logs',
            old_name='user_id',
            new_name='User_id',
        ),
    ]
