# Generated by Django 3.2.3 on 2021-08-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0007_rename_user_id_student_logs_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_V1.student_details')),
            ],
        ),
    ]
