# Generated by Django 3.2.3 on 2021-09-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0008_sticky_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_logs',
            options={'verbose_name_plural': 'Student Logs'},
        ),
    ]
