# Generated by Django 3.2.3 on 2021-08-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0008_sticky_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticky_notes',
            options={'verbose_name_plural': 'Sticky Notes'},
        ),
        migrations.AlterModelOptions(
            name='student_logs',
            options={'verbose_name_plural': 'Student Logs'},
        ),
    ]
