# Generated by Django 3.2.3 on 2021-09-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0009_alter_student_logs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_notes',
            options={'verbose_name_plural': 'User Notes'},
        ),
    ]
