# Generated by Django 3.2.3 on 2021-08-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0009_auto_20210815_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sticky_notes',
            new_name='User_notes',
        ),
    ]
