# Generated by Django 3.2.3 on 2021-08-15 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_V1', '0010_rename_sticky_notes_user_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_notes',
            options={'verbose_name_plural': 'User Notes'},
        ),
        migrations.RemoveField(
            model_name='user_notes',
            name='Student_id',
        ),
        migrations.AddField(
            model_name='user_notes',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_V2.customuser'),
            preserve_default=False,
        ),
    ]
