# Generated by Django 3.2.3 on 2021-10-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0009_auto_20210918_1014'),
        ('student_V1', '0010_alter_user_notes_options'),
    ]

    operations = [
    ]
