# Generated by Django 3.2.3 on 2021-08-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_V1', '0009_auto_20210805_0157'),
        ('student_V1', '0011_auto_20210815_0139'),
    ]

    operations = [
    ]
